model: 'XCLIP_DeMamba'
tuning_mode: 'sft'
task: 'many2many'

save_dir: './results/XCLIP_Mamba_2'

max_epoch: 1
bath_per_epoch: 2800

train_batch_size: 32
val_batch_size: 32
num_workers: 16
lr: 0.0002
# lr: 0.000001
